# Generated by Django 2.2.6 on 2019-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20191103_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
