# Generated by Django 2.2.6 on 2019-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_libro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='publicacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen'),
        ),
    ]
