# Generated by Django 2.2.6 on 2019-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20191103_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(to='proyecto.Autor'),
        ),
    ]
