# Generated by Django 2.2.6 on 2019-11-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_libro_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='created',
        ),
    ]
