# Generated by Django 2.2.6 on 2019-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20191103_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='encargado',
        ),
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagen'),
        ),
    ]
